// <auto-generated />
namespace IT_Lab3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class changedlist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedlist));
        
        string IMigrationMetadata.Id
        {
            get { return "202505101624373_changed-list"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
